### ISSUE TITLE
Ошибки при импорте.

### ISSUE THREAD

**Issue by ManulInTheBag** [PavelBlend/Blender_WarCraft-3#3]
Версия Blender - 2.78.
Ни в один из разов, в которые скрипт завершил импорт без видимых ошибок (он часто ругается на строку 140 в importer.py по причине KeyError, при этом я наблюдаю корелляцию данного явления с дубляцией названия кости, чем часто страдают .mdx, но прямой связи не нашел, при отключении строки 140 ругается на 142, при отключении 142 он начинает ругаться на дубли уже практически прямым текстом в скрипте импорта анимаций, так как не может создать уже существующую FCurve), он не смог импортировать анимации. В исходных моделях они всегда существовали. Плюс полигоны почему-то имеют очень острые края (я не уверен, что это проблема данного плагина, но на всякий случай напишу).
Какие-нибудь идеи, как это возможно пофиксить? Дубли-то ошибка самой модели и это исправимо, но вот почему плагин и корректные с этой точки зрения модели не желает анимировать - вопрос открытый.

**Comment by ManulInTheBag** [comment]
Упс, я идиот. Извиняюсь, нет никакой ошибки.

**Comment by Kaizer123456** [comment]
А что если у меня версия блендера может быть только 2.79, и мне нужен скрипт MDL? Как мне его установить если постоянно появляются всплывающие окна с ошибками, либо просто не появляется строчки с активацией скрипта но условно он установился? Пожалуйста помогите
